### ISSUE TITLE
Investigate "off" ESLint rules

### ISSUE THREAD

**Issue by natesulat** [kiva/protocol-architecture#10]
During the TSLint -> ESLint migration, a lot of errors were generated by the following rules, and so in large part they were turned off or disabled:

```
"@typescript-eslint/no-unsafe-assignment": "off",
"@typescript-eslint/no-unsafe-member-access": "off",
"@typescript-eslint/no-unsafe-argument": "off",
"@typescript-eslint/no-unsafe-call": "off",
"@typescript-eslint/no-unsafe-return": "off",
"@typescript-eslint/require-await: "off",
```

This was initially tracked here https://github.com/kiva/protocol-gateway/issues/55, but I'm opening up a ticket in this repo, too, because this was a general issue across our backend stack.

It may be there are other rules that we want to turn to "warn" or "error" across our stack.

**Comment by matt-raffel-kiva** [comment]
Closing issue as part of project shutdown
