### ISSUE TITLE
Review / update base images for docker images

### ISSUE THREAD

**Issue by voutasaurus** [kiva/protocol-architecture#5]
We produce a variety of docker images that are built on top of publicly available base images.

We have not recently updated those base images.

This task is to review the base images for each of our docker images and determine the feasibility of updating them (completing that update where feasible).

 Review each repo:
- [x] aries-controller (test)
- [x] protocol-common (test)
- [ ] aries-controller (test and deploy)
- [ ] protocol-common (test and deploy)
- [ ] guardian-bio-auth (kivaprotocol/bioauth and kivaprotocol/bioanalyzer)
- [x] protocol-gateway (kivaprotocol/protocol-gateway)
- [x] protocol-reporting (kivaprotocol/protocol-reporting)
- [x] aries-key-guardian (kivaprotocol/aries-key-guardian)
- [x] protocol-aries
- [ ] protocol-implementation-honduras

**Comment by voutasaurus** [comment]
Potential new base images for node:

Sticking with node14 (EOL 2023-04-30) [14.19.1-alpine3.15](https://hub.docker.com/layers/node/library/node/14.19.1-alpine3.15/images/sha256-52679161d625955867c71f808cf96f4222e24a5c695a39a61d0de65f85e829a6?context=explore)

Upgrading to node16 (EOL 2024-04-30) [16.14.2-alpine3.15](https://hub.docker.com/layers/node/library/node/16.14.2-alpine3.15/images/sha256-eb705b1081d837fba1d980fa4dd25bc729661140b1e6a7cc6e499fb54adddb09?context=explore)

**Comment by matt-raffel-kiva** [comment]
Closing issue as part of project shutdown
