### ISSUE TITLE
better solution for  "agent" failed to come up before the "controller"

### ISSUE THREAD

**Issue by matt-raffel-kiva** [kiva/protocol-architecture#7]
From time to time we see an error message about a walletId or walletKey failing validation, as services are starting up.   This happens in CI and locally (and most likely in AWS as well).  The problem is the acapy agent hasn't completely initialized before the controller starts up its initialization/setup.   Our solution has been to simply wait 30 seconds or so.  This is not ideal and can still fail.

Agents do have a /status and /status/ready endpoint that we could be using.  

If we can get a reliable response from the an agent on this endpoint, we should have our wait script use that instead of a hardcoded 30 second wait.

This issue applies to all of our acapy agents + their controllers.

**Comment by ghost** [comment]
Do you think this is more of a general architecture point around agents or is it specific to rnp-agent? If it's the latter, I think this issue would belong in the protocol-implementation-honduras repo.

**Comment by matt-raffel-kiva** [comment]
Closing issue as part of project shutdown
